better

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -14,43 +14,43 @@ jobs:
     name: Check Configuration
     runs-on: ubuntu-latest
     steps:
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ vars.AWS_REGION }}
-        
-      - name: Checkout
-        uses: actions/checkout@v3
+    - name: Configure AWS Credentials
+      uses: aws-actions/configure-aws-credentials@v2
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ vars.AWS_REGION }}
+      
+    - name: Checkout
+      uses: actions/checkout@v3
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.4.6
-            
-      - name: Terraform fmt
-        id: fmt
-        continue-on-error: true
-        run: |
-            format_check=$(terraform fmt -check)
-            if [ $? -ne 0]; 
-            then
-              # Format check failed because there are 
-              echo "# Format check failed on the following files:" >> $GITHUB_STEP_SUMMARY
-              for i in ${format_check};
-              do
-                echo "- ${i}" >> $GITHUB_STEP_SUMMARY
-              done
-            fi
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v2
+      with:
+        terraform_version: 1.4.6
+          
+    - name: Terraform fmt
+      id: fmt
+      continue-on-error: true
+      run: |
+          format_check=$(terraform fmt -check)
+          if [ $? -ne 0]; 
+          then
+            # Format check failed because there are 
+            echo "# Format check failed on the following files:" >> $GITHUB_STEP_SUMMARY
+            for i in ${format_check};
+            do
+              echo "- ${i}" >> $GITHUB_STEP_SUMMARY
+            done
+          fi
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
+    - name: Terraform Init
+      id: init
+      run: terraform init
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate
+    - name: Terraform Validate
+      id: validate
+      run: terraform validate
 
   plan:
     needs: [check]
@@ -65,6 +65,9 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ vars.AWS_REGION }}
+
+    - name: Checkout
+      uses: actions/checkout@v3
 
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
